### ISSUE TITLE
Real Path null

### ISSUE THREAD

**Issue by Ankurjain30** [hmkcode/Android#23]
I used your mainactivity and realpathutil code. Unfortunately it is not sowing Real path in android Kitkat API 19. Pls help.

**Comment by Ankurjain30** [comment]
Here is Log.
12-05 21:31:37.586 12735-12735/jss.kitkatfile W/System.err: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
12-05 21:31:37.586 12735-12735/jss.kitkatfile W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:409)
12-05 21:31:37.586 12735-12735/jss.kitkatfile W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:78)
12-05 21:31:37.586 12735-12735/jss.kitkatfile W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:105)
12-05 21:31:37.586 12735-12735/jss.kitkatfile W/System.err:     at android.content.ContentResolver.openInputStream(ContentResolver.java:627)
12-05 21:31:37.586 12735-12735/jss.kitkatfile W/System.err:     at jss.kitkatfile.Git.setTextViews(Git.java:98)
12-05 21:31:37.586 12735-12735/jss.kitkatfile W/System.err:     at jss.kitkatfile.Git.onActivityResult(Git.java:79)
12-05 21:31:37.586 12735-12735/jss.kitkatfile W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:5603)
12-05 21:31:37.586 12735-12735/jss.kitkatfile W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3528)
12-05 21:31:37.586 12735-12735/jss.kitkatfile W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3575)
12-05 21:31:37.586 12735-12735/jss.kitkatfile W/System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:139)
12-05 21:31:37.596 12735-12735/jss.kitkatfile W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
12-05 21:31:37.596 12735-12735/jss.kitkatfile W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-05 21:31:37.596 12735-12735/jss.kitkatfile W/System.err:     at android.os.Looper.loop(Looper.java:149)
12-05 21:31:37.596 12735-12735/jss.kitkatfile W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5257)
12-05 21:31:37.596 12735-12735/jss.kitkatfile W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
12-05 21:31:37.596 12735-12735/jss.kitkatfile W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
12-05 21:31:37.596 12735-12735/jss.kitkatfile W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
12-05 21:31:37.596 12735-12735/jss.kitkatfile W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
12-05 21:31:37.596 12735-12735/jss.kitkatfile W/System.err:     at dalvik.system.NativeStart.main(Native Method)
12-05 21:31:37.596 12735-12735/jss.kitkatfile W/System.err: Caused by: libcore.io.ErrnoException: open failed: EISDIR (Is a directory)
12-05 21:31:37.606 12735-12735/jss.kitkatfile W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:398)
12-05 21:31:37.606 12735-12735/jss.kitkatfile W/System.err: 	... 18 more
12-05 21:31:37.606 12735-12735/jss.kitkatfile D/HMKCODE: Build.VERSION.SDK_INT:19
12-05 21:31:37.606 12735-12735/jss.kitkatfile D/HMKCODE: URI Path:/document/6464-3031:WhatsApp/WhatsApp Images/IMG-20160514-WA0004.jpg
12-05 21:31:37.606 12735-12735/jss.kitkatfile D/HMKCODE: Real Path:

**Comment by siriparaandroid** [comment]
Thanks, it is really useful

**Comment by carlosalfonso2014** [comment]
Thanks a lot!!
